name: blue_anura
description: Flutter project for Citizen Scientist photo surveys

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.3+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  platform_date_picker: ^0.0.4+1
  intl: ^0.17.0-nullsafety.2
  rflutter_alert: ^1.1.0
  # mask_text_input_formatter: ^1.1.0
  flutter_masked_text: ^0.8.0
  location: ^3.2.1
  devicelocale: ^0.3.3
  form_validator: ">=0.1.7 <2.0.0"
  share: ">=0.6.5+4 <2.0.0"
  shared_preferences: '>=0.5.12+4 <2.0.0'
  flutter_login:
    path: lib/views/auth/widgets/flutter_login
#  flutter_login: ^1.0.14
#  image: ^2.1.19
  path_provider: ^1.6.24
#  rxdart: ^0.25.0
  camerawesome: ^0.2.1
#  gallery_saver:
#    path: lib/views/camera/widgets/gallery_saver
#  gallery_saver: ^2.0.1
  permission_handler: ^5.0.1+1
  flutter_exif_plugin:
    path: lib/views/camera/widgets/flutter_exif
#  flutter_exif_plugin: ^0.0.4
  package_info: ^0.4.3+2

  exif: ^1.0.3
  adaptive_dialog: ^0.9.3

  device_info: ^1.0.0

#  # The following was for setting the app icon...
#  # Uncomment to reset the app icon
#  # After setting up flutter_icons below run:
#  #  á… flutter pub run flutter_launcher_icons:main
#  flutter_launcher_icons: "^0.8.0"
#
## Uncomment to following to setup app icon
#flutter_icons:
#  # Use this png for android and set android: true, ios: false
#  image_path: "assets/images/cba-864-transparent.png"
#  android: true
#  # Use this png for ios and set android: false, ios: true
##  image_path: "assets/images/cba-864-blue.png"
#  ios: false

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/cba-96-transparent.png

  fonts:
    - family: Grandstander
      fonts:
        - asset: assets/fonts/Grandstander-Regular.ttf
          weight: 400
        - asset: assets/fonts/Grandstander-Italic.ttf
          style: italic
